# Generated by Django 2.0.3 on 2018-03-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_image', models.FileField(upload_to='documents/')),
                ('right_image', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vote_left', models.IntegerField(default=0)),
                ('vote_right', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
